### ISSUE TITLE
Add guestbook record deletion

### ISSUE THREAD

**Issue by vermiculus** [luminus-framework/guestbook#11]
Most applications have some 'invisible' two-way communication between client and server. It would be very helpful to have a basic example of getting the appropriate information back to the server to do some task, such as record deletion.

Nothing fancy is necessary; a 'delete' hyperlink after the timestamp should be sufficient and *very* helpful. Once I can see the example code, I'd be more than happy to write a first-draft edit to the docs.

**Comment by yogthos** [comment]
I'll take a look at adding the delete functionality to the example. It would work the same way as adding messages though, you'd call call a route on the server and it would complete the task and redirect back to the page. Effectively, it would work exactly the same as adding a message except it would call a different database query.

**Comment by vermiculus** [comment]
After playing with a bit, clearing my head with some CS:GO, and then coming back to it, I did eventually figure it out.

```clojure
(defn delete-message! [{:keys [params]}]
  (db/delete-message! params)
  (redirect "/"))

(defroutes home-routes
  (GET "/" request (home-page request))
  (POST "/" request (save-message! request))
  (GET "/delete" request (delete-message! request))
  (GET "/about" [] (about-page)))
```
```sql
--name:delete-message!
-- deletes a message
DELETE FROM guestbook
WHERE id = :id
```

The tricky part (for me, being somewhat of a web know-nothing) was that the URL linked to by the `delete` link needed to provide parameters in the form of `/delete?id={{item.id}}` instead of my assumption of `/delete/{{item.id}}`. I guess I'm trying to say this idea is perhaps non-obvious to someone effectively new to webapp development and would be valued in the tutorial.

On the other hand, I'll admit that I know what I don't know here and say this could be a 'slippery slope'. Nobody's going to want to wade through a giant series of tutorials that demonstrate everything you might want to do :smile:

**Comment by yogthos** [comment]
You could have done it the other way as well actually. You'd just have to change the route as follows:

```clojure
(GET "/delete/:item-id" [item-id] (delete-message! item-id))
```

It's better to use the proper HTTP code as well:

```clojure
(DELETE "/delete/:item-id" [item-id] (delete-message! item-id))
```
Then in the form, you set the corresponding method:

```xml
<form action="/delete/{{item.id}}" method="delete">
  {% csrf-token %}  
  <input type="submit" value="Delete">
</form>
```

I'll take a look at adding this as it's likely to be helpful to others as well.

**Comment by vermiculus** [comment]
Unfortunately, vermiculus/clj-guestbook@1c240a0ef0d6a735ce2367dc8497febbb199c992 gives me a 404.

I recognize that GET was far from ideal, but I was acting on [this SO post](//stackoverflow.com/a/5823789/1443496) – is this information finally outdated?

**Comment by yogthos** [comment]
right, sorry `DELETE` won't work from a form. However, it would still be better to use a `POST`, as `GET` indicates reading data as opposed to modifying it. The other reason is that `POST` will be secured using the CSRF token, where it's not required for `GET` method calls.
