### ISSUE TITLE
"lein run" isn't enough, please add more info to Readme.md 

### ISSUE THREAD

**Issue by mattiasw2** [luminus-framework/guestbook#12]
Just cloned and made "lein run", and noticed the database wasn't created. So, something more needed.

I was however very impressed with the error page should on localhost:3000

```
Retrieving fipp/fipp/0.5.2/fipp-0.5.2.jar from clojars
Retrieving transduce/transduce/0.1.0/transduce-0.1.0.jar from clojars
12:41:05.091 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
15-Sep-19 12:41:07 x220 INFO [guestbook.core] - nREPL server started on port 7000
15-Sep-19 12:41:07 x220 INFO [guestbook.handler] -
-=[guestbook started successfully using the development profile]=-
12:41:08.081 INFO  [org.projectodd.wunderboss.web.Web] (main) Registered web context /
15-Sep-19 12:41:08 x220 INFO [guestbook.core] - server started on port: 3000
org.h2.jdbc.JdbcSQLException: Table "GUESTBOOK" not found; SQL statement:
SELECT * from guestbook [42102-187]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.Parser.readTableOrView(Parser.java:5261)
        at org.h2.command.Parser.readTableFilter(Parser.java:1235)
        at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1874)
```

**Comment by mattiasw2** [comment]
lein run migrate

followed by

   lein run

makes it work

**Comment by yogthos** [comment]
thanks, updated the readme

**Comment by fabianherrera** [comment]
Hi Guys,
Why Lein run migrate doesn't work after first time:

C:\Users\Documents\GitHub\x>lein run migrate
read config from resource: "config.edn"
read config from file: ".lein-env"
2017-11-21 16:06:30,726 [main] INFO  migratus.core - Starting migrations
2017-11-21 16:06:32,485 [main] INFO  migratus.core - Ending migrations
C:\Users\Documents\GitHub\x>

And, there is not any change in database.

**Comment by yogthos** [comment]
The migrate command will only run migrations that haven't been previously run. When it runs the first time, it should create the db, and subsequent runs will skip migrations that have already been applies unless you roll back.
