### ISSUE TITLE
Table "GUESTBOOK" not found

### ISSUE THREAD

**Issue by ILoveHubGit** [luminus-framework/guestbook#19]
I'm trying to get the clojure application "guestbook" working. But when I run the application and browse to it at localhost:3000 I get an error:

org.h2.jdbc.JdbcSQLException at /
Table "GUESTBOOK" not found; SQL statement:
SELECT * FROM guestbook [42102-192]

I think something during "lein run migrate" is not working. The output I get from this is:

read config from resource: "config.edn"
read config from file: ".lein-env"
2016-09-12 21:34:43,273 [main] INFO migratus.core - Starting migrations 
2016-09-12 21:34:43,328 [main] INFO migratus.database - creating migration table 'schema_migrations' 
2016-09-12 21:34:43,348 [main] INFO migratus.core - Ending migrations

I thought I've seen somewhere that it should give information about the tables as well, but I can't find it anymore

Please help

**Comment by yogthos** [comment]
You have to run migrations with `lein run migrate` first to initialize the database.

**Comment by ILoveHubGit** [comment]
This is the output after the initial run of `lein run migrate`.
It makes no difference if I change the in resources/migrations or not. It looks like they are ignored

**Comment by ILoveHubGit** [comment]
I downloaded the zip file https://media.pragprog.com/titles/dswdcloj2/code/dswdcloj2-code.zip
and unpacked the guestbook application.
Without making any changes to the files I ran `lein run migrate` The result is an empty database without any tables.
This is the content of the profiles.clj file (wihtout the comments)
`{:profiles/dev  {:env {:database-url "jdbc:h2:./guestbook_dev.db"}}
 :profiles/test {:env {:database-url "jdbc:h2:./guestbook_test.db"}}}`

In resources/migrations there are two files, one to add a table (up) and one to drop the table (down)

**Comment by ILoveHubGit** [comment]
I got a database from a friend and if I add this to the root of my project and run `lein run` I can start the application correctly in the browser and add new comments without any problems.

Therefore I'm now convinced that something goes wrong during `lein run migrate`.

Is there a way to debug this process?

**Comment by lacarmen** [comment]
I can't reproduce the problem. From the output of your `lein run migrate` it looks like no migrations are found. Where are your migrations located and what are they called?

Here's what I get with a fresh project:

```
[~/src] ⋊> lein new luminus guestbook +h2 
Generating a Luminus project.
                                                                                                                                                                                                                   
[~/src] ⋊> cd guestbook/
                                                                                                                                                                                                                   
[~/s/guestbook] ⋊> lein run migrate
read config from resource: "config.edn"
read config from file: ".lein-env"
2016-09-13 15:30:30,808 [main] INFO  migratus.core - Starting migrations 
2016-09-13 15:30:31,103 [main] INFO  migratus.database - creating migration table 'schema_migrations' 
2016-09-13 15:30:31,141 [main] INFO  migratus.core - Running up for [20160913153009] 
2016-09-13 15:30:31,142 [main] INFO  migratus.core - Up 20160913153009-add-users-table 
2016-09-13 15:30:31,162 [main] INFO  migratus.core - Ending migrations
```

**Comment by ILoveHubGit** [comment]
Yes this is exactly what I get if I run it on my laptop. But I want to be able to develop on my desktop as well and here this doesn't work.
My migrations are in resources/migrations and they're called:
- 20160913205400-add-users-table.down.sql
- 20160913205400-add-users-table.up.sql

I attached a file with the tree structure of the project
[tree.txt](https://github.com/luminus-framework/guestbook/files/470651/tree.txt)

**Comment by yogthos** [comment]
The file structure looks right, and I'm not able to reproduce the problem locally either. I've ran migrations from the guestbook project in the zip, and it created the table for me.

One thing to check is that you don't have an existing `guestbook_dev.db.mv.db` database file. If you do, try deleting it and running the migrations again. If the migrations table already exists and has the migration marked as completed, the migration won't be rerun.

**Comment by ILoveHubGit** [comment]
I tried today the following:

1. I created a new folder Projects in Home
2. Ran `lein new luminus guestbook +h2`
       Response was: `Generating a Luminus project` and a folder guestbook was created.
3. Then `cd guestbook`
4. Then `lein run migrate`
       Response was: 
`2016-09-14 21:42:13,203 [main] INFO  migratus.core - Starting migrations 
2016-09-14 21:42:13,476 [main] INFO  migratus.database - creating migration table 'schema_migrations' 
2016-09-14 21:42:13,495 [main] INFO  migratus.core - Ending migrations`
These same lines are in the guestbook.log file.

A database is created. I attached it and as you can see there is no table created inside this database.

In the project.clj file I see one dependency `luminus-migrations "0.2.6"` and one plugin `migratus-lein "0.4.1"` that could, in my opinion,  have something to do with the migrate proces. However, I could be wrong since I'm a newby :-)

In the repository in the `.m2` folder I can find these with the correct version number but also a `migratus "0.8.13"`

Which of these is responsible for the migrate?
Is there a way to get more feedback during the migrate process?

[guestbook_dev.db.mv.db.zip](https://github.com/luminus-framework/guestbook/files/473336/guestbook_dev.db.mv.db.zip)
[tree.txt](https://github.com/luminus-framework/guestbook/files/473357/tree.txt)

**Comment by ILoveHubGit** [comment]
Correction: I have `migratus "0.8.28"` also.

**Comment by yogthos** [comment]
The `luminus-migrations` library is the wrapper for `migratus` that runs migrations. It does look like you have the latest version. The plugin is only used for generating migration files.

The migration files do appear to be in the right place as, so I'm really not sure why it wouldn't be finding them in your setup. I've tried this on a few machines and I'm not able to reproduce the problem myself unfortunately.

You could change the log level to debug or trace to get more info from migratus. You just have to change the default log level in `/env/dev/resources/logback.xml`:

```xml
 <root level="TRACE">
         <appender-ref ref="STDOUT" />
         <appender-ref ref="FILE" />
 </root>
```
You should see something like this in the log:

```
lein run migrate
2016-09-14 16:49:42,793 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
read config from resource: "config.edn"
read config from file: ".lein-env"
2016-09-14 16:49:43,359 [main] INFO  migratus.core - Starting migrations
2016-09-14 16:49:43,548 [main] INFO  migratus.database - creating migration table 'schema_migrations'
2016-09-14 16:49:43,570 [main] INFO  migratus.core - Running up for [20160914164346]
2016-09-14 16:49:43,571 [main] INFO  migratus.core - Up 20160914164346-add-users-table
2016-09-14 16:49:43,574 [main] DEBUG migratus.database - found 1 up migrations
2016-09-14 16:49:43,574 [main] TRACE migratus.database - executing CREATE TABLE users
(id VARCHAR(20) PRIMARY KEY,
first_name VARCHAR(30),
last_name VARCHAR(30),
email VARCHAR(30),
admin BOOLEAN,
last_login TIME,
is_active BOOLEAN,
pass VARCHAR(300));

2016-09-14 16:49:43,576 [main] DEBUG migratus.database - marking 20160914164346 complete
2016-09-14 16:49:43,583 [main] INFO  migratus.core - Ending migrations
```

**Comment by ILoveHubGit** [comment]
I'm looking through the JAR files in the .m2 folder and what I found is a dependency to `com.h2database/h2 "1.4.190"` in the `project.clj` file of the `migratus-0.8.28.jar`. In the guestbook `project.clj` version "1.4.192" is set as dependency and version "1.4.190" was missing from my `.m2/repository`.
I downgraded the guestbook `project.clj` to version "1.4.190", removed the database and ran `lein run migrate` but no success yet. (version "1.4.190" was downloaded)

I upgraded the project the guestbook `project.clj` to version "1.4.192", removed the database and ran `lein run migrate` but again no success yet.

**Comment by yogthos** [comment]
The fact that you're not getting any errors seems to indicate that migratus is simply not finding the migration files under `resources/migrations`. I'm not sure why that happens with your setup and not others however.

**Comment by ILoveHubGit** [comment]
Thanks for the support. But with the TRACE or DEBUG option I still get the same output.

Test1: I tried renaming the `resources` folder and this gave an error and created a new empty `resources` folder. 
Test2: Renaming the sub-folders of `resources` folder gave only  an error for the `templates` folder. Restoring this to the correct name gave me again the output as described above. So even if the migrations folder is not available `lein run migrate` does not complain about this. But maybe that is expected behaviour.
Test3: I installed Ubuntu 16.04.1 64bit in a VM and everything works flawlessly.

Conclusion: There is something wrong with my Ubuntu 16.04 in combination with migratus. I've no clue what and how to repair it. Everything else seems to work perfectly

**Comment by yogthos** [comment]
Yeah, that sounds quite strange indeed. The fact that it works on a fresh Ubuntu install, but not on your current setup is rather odd. I can't really think of anything system specific that should cause migratus not to find files.

Only other thing I can think of is to try a specific migration explicitly to see what happens, e.g:

    lein run migrate 20111206154000

**Comment by ILoveHubGit** [comment]
Hi yogthos,

I didn't mention it but I've tried this multiple times. I even first used `touch` on the files to make sure their time stamp was of today. But also then they were not picked up by migratus.
Maybe I'll reinstall my PC and see if the problem is solved then.

Thanks a lot

**Comment by yogthos** [comment]
Yeah, sorry we couldn't figure it out. The fact that it only happens with that particular setup makes it tricky to troubleshoot. Hopefully everything will just work with a new setup.

**Comment by kucerm2** [comment]
I had the same problem on Windows 10, the solution was to run the command in Administrator mode.

**Comment by kucerm2** [comment]
I have the same problem on W10,  the solution was to rewrite table name to uppercase in queries.sql.
```sql
-- :name save-message! :! :n
-- :doc creates a new message
INSERT INTO QUESTBOOK
(name, message, timestamp)
VALUES (:name, :message, :timestamp)

-- :name get-messages :? :*
-- :doc selects all available messages
SELECT * FROM QUESTBOOK
```

**Comment by timmyjose** [comment]
I tried it - same issue. Disappointing since I had hoped to work through the book.

**Comment by shashank19909** [comment]
To solve this issue I followed these steps
1. Delete any existing guestbook_dev.db.mv.db & guestbook_dev.db.trace.db
2. run the command `lein run migrate` - If the migration is successful you will see new guestbook_dev.db.mv.db & guestbook_dev.db.trace.db created in the project again
3. run `lein repl`
4. run `(start)`
5. run `(mount/start #'guestbook.db.core/*db*)` - you should see this - `{:started []}`
6. Now as the book says run `(get-messages)` - you should see `()` as the output

@timmyjose try this and see. Don't give up on the book this early :)

**Comment by NPException** [comment]
To anyone coming here looking for a solution to this frustrating problem like me:  
This issue is caused by changes to ClassLoader hierarchies in Java 9.

More specifically, the migrations could not be found as a result of this issue in a library used by Migratus: https://dev.clojure.org/jira/browse/CLASSPATH-8

To solve this issue, there are three options:

## Option 1: Update the version of `luminus-migrations`

In your `project.clj`, update `luminus-migrations` to version `0.5.0` or higher. That version is using Migratus version 1.0.6 which solves the [migration discoverability issue](https://github.com/yogthos/migratus/blob/master/CHANGES.md#106).

_(This is what I'll be doing. I'm using the most recent version `0.6.4` at the time of writing. I'll update this comment if I run into any issues because of the version change when working through the book)_

## Option 2: Add a workaround yourself

If you don't want to change the version of the library, you can add this workaround code to your `guestbook/core.clj`:

```clojure
(extend-type java.lang.ClassLoader
  clojure.java.classpath/URLClasspath
  (urls [_]
    (map #(clojure.java.io/as-url (clojure.java.io/file %))
         (clojure.string/split (System/getProperty "java.class.path")
                               (re-pattern java.io.File/pathSeparator)))))
```

_(Taken from the comment by [Benjamin Albrecht on the mentioned JIRA Ticket](https://dev.clojure.org/jira/browse/CLASSPATH-8?focusedCommentId=47650&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-47650))_

## Option 3: Stick to Java 8

If you make sure that Leiningen and your code is only running on Java 8, you should be fine too.

--------------

I hope that this comment will save some people from the frustrations I went through. Have fun with the book, folks! :)

Happy coding,
NPE
