### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ovsemykin** [luminus-framework/guestbook#20]
![bug](https://cloud.githubusercontent.com/assets/11682023/25048141/6c3cc684-2143-11e7-8049-8511c7908466.jpg)

**Comment by yogthos** [comment]
Have you run migrations, it look like it can't find the table or the connection settings might be wrong. You have to add a migration file and then run `lein run migrate` to initialize the db.

**Comment by yogthos** [comment]
@ovsemykin  are you still having problems with the database or can we close this one?

**Comment by ovsemykin** [comment]
Where can I get the migration file?

**Comment by ovsemykin** [comment]
I ran the migration process

**Comment by yogthos** [comment]
Take a look at the [migration docs](http://www.luminusweb.net/docs/migrations.md) for the details.
