### ISSUE TITLE
Failing to connect remote repl-server

### ISSUE THREAD

**Issue by soulawaker** [luminus-framework/guestbook#22]
I've tried to connect remote (not localhost, another machine in same local LAN network) guestbook repl-server in guestbook docker container with default 7000 port.
Accessing remote http-server with default 3000 port is ok.
So I assumed my docker, firewall etc. network configurations are not problems. 
Do I need to add any configuration in guestbook code?

![2017-12-24 18 12 45](https://user-images.githubusercontent.com/5372217/34325539-d8d69084-e8d7-11e7-9638-8c3afffd570f.png)

**Comment by yogthos** [comment]
A couple things to check are that you exposing the nREPL port in the Dockerfile, and that nREPL is listening for external connections. By default, nREPL is configured to only listen to localhost as security measure. So, the app could be listening for local connections within the container.

**Comment by soulawaker** [comment]
Ok, I added bind address for nREPL server. Thanks for confirmation.
