### ISSUE TITLE
guestbook_test.db.mv.db locked after (stop) and (start) in REPL

### ISSUE THREAD

**Issue by soulawaker** [luminus-framework/guestbook#23]
After `lein test-refresh` I modified `home.clj` in routes folder.
Then `(stop)` and `(start)` in REPL for checking its changes.
In REPL, exception message printed.
```
read config from file: ".lein-env"
IllegalStateException The file is locked: nio:/root/guestbook/guestbook_test.db.mv.db [1.4.192/7]  org.h2.mvstore.DataUtils.newIllegalStateException (DataUtils.java:773)
``` 

Anyway, I undo my job below order.
1. `Ctrl-c` in `lein test-refresh` terminal.
2. undo my code in `home.clj`.
3. `(stop)` and `(start)` in REPL. -- no error.
4. `lein test-refresh` 
Then below message printed in terminal
```
java.lang.IllegalStateException: The file is locked: nio:/root/guestbook/guestbook_test.db.mv.db [1.4.192/7]
```
I think this lock continued since first exception occured, though `lein test-refresh` process terminated.
Am I missing any safe termination method or any components missing it?

**Comment by yogthos** [comment]
This is a similar problem to [this](https://github.com/luminus-framework/luminus-template/issues/292) issue. Since tests share environment config with the dev profile they end up stepping on each other. I'll take a look at improving the config setup to avoid this.

**Comment by yogthos** [comment]
I finally got around to resolving this. The new template no longer uses `profiles.clj` to track environment variables. Instead, there are two separate files called `dev-config.edn` and `test-config.edn` for tracking dev and test configurations respectively.

**Comment by yogthos** [comment]
I updated the guestbook example, let me know if that solves the issue for you.

**Comment by soulawaker** [comment]
Ok. It worked. I'll close this issue. Thanks.
