### ISSUE TITLE
Date filter (in home.html) throwing exception in tutorial

### ISSUE THREAD

**Issue by tsaixingwei** [luminus-framework/guestbook#24]
When working through the tutorial (http://www.luminusweb.net/docs), I encountered the following exception:

> On filter body 'item.timestamp|date:"yyyy-MM-dd HH:mm"' and filter 'date:"yyyy-MM-dd HH:mm"' this error occurred:2018-11-17T07:08:34.151 is not a valid date format.

Going through the source, it seems that the java.sql.Timestamp values from the database are being converted to java.time.LocalDateTime instances when the jdbc/IResultSetReadColumn protocol is being extended (in guestbook.db.core.clj). However, selmer.filters/fix-date function is not converting such java.time.LocalDateTime instances to org.joda.time.DateTime format, and is thus throwing the exception above.

**Comment by yogthos** [comment]
Thanks for the heads up. I think the right thing to do is to update Selmer to use the new Java time API instead of Joda time. I'll take a look shortly.

**Comment by yogthos** [comment]
I pushed out a new version of Selmer, and Luminus template using it. If you update to `[selmer "1.12.4"]` the error should go away. Let me know if everything looks good on your end.

**Comment by tsaixingwei** [comment]
Yeah... updating to Selmer 1.12.4 fixed the problem. Thanks.

**Comment by md1frejo** [comment]
I have the same problem from the tutorial and I am using selmer-1.12.18. 
the error:
On filter body 'item.timestamp|date:"yyyy-MM-dd HH:mm"' and filter 'date:"yyyy-MM-dd HH:mm"' this error occurred:1576503239740 is not a valid date format.
Application FramesAll Frames

any suggestions?
