### ISSUE TITLE
Minor typo in template

### ISSUE THREAD

**Issue by Smulligan85** [luminus-framework/guestbook#4]
This is a minor comment typo, but thought I'd bring it to your attention. The following code in queries.sql has user misspelled as used.

    -- name: get-user
    -- retrieve a used given the id.
    SELECT * FROM users
    WHERE id = :id

Should be ```-- retrieve a user given the id.```

**Comment by yogthos** [comment]
thanks

**Comment by yogthos** [comment]
should be fixed in the latest version
