### ISSUE TITLE
Starting server fails

### ISSUE THREAD

**Issue by systemovich** [luminus-framework/guestbook#5]
After cloning the repository, I executed:

    $ lein ring server

But I got this error:

> Exception in thread "main" java.io.FileNotFoundException: Could not locate ring/adapter/jetty__init.class or ring/adapter/jetty.clj on classpath., compiling:(ring/server/standalone.clj:1:1)

**Comment by yogthos** [comment]
The new versions of Luminus no longer use `lein-ring` plugin to start the server. The app should be started using `lein run` instead.

**Comment by systemovich** [comment]
Thanks. I also had to run `lein run migrate` first.
