### ISSUE TITLE
lein run: error.html (no such file)

### ISSUE THREAD

**Issue by sdimitro** [luminus-framework/guestbook#8]
Hi there!

That's is just a minor issue, but after running the migration and doing `lein run` I get the following:
```
java.io.FileNotFoundException: /home/serapheim/reborn/tutora/versions/guestbook/resources/templates/error.html (No such file or directory)
```

It is not a big issue, I just made an empty error.html file in the templates directory and everything ran fine. I thought about making an issue just in case though.

**Comment by yogthos** [comment]
thanks, I just checked it in with the latest update
